---
- name: Register with activationkey and auto-subscribe to available content.
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_activation_key }}"
    org_id: "{{ rhsm_org_id }}"